# Generated by Django 4.2.7 on 2025-03-05 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("all_time", "All Time"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_recorded", models.DateField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.player",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["period", "score"], name="leaderboard_period_5afa16_idx"
                    ),
                    models.Index(
                        fields=["date_recorded"], name="leaderboard_date_re_4a8717_idx"
                    ),
                ],
                "unique_together": {("player", "period", "date_recorded")},
            },
        ),
    ]
