# Generated by Django 4.2.7 on 2025-03-05 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                ("level_id", models.AutoField(primary_key=True, serialize=False)),
                ("difficulty", models.IntegerField(default=1)),
                ("tile_layout", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Tile",
            fields=[
                ("tile_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tile_type",
                    models.CharField(
                        choices=[
                            ("bamboo", "Bamboo"),
                            ("leaf", "Leaf"),
                            ("panda", "Panda"),
                            ("fish", "Fish"),
                            ("carrot", "Carrot"),
                            ("fire", "Fire"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position_x", models.IntegerField()),
                ("position_y", models.IntegerField()),
                ("position_z", models.IntegerField(default=0)),
                (
                    "game_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.gamesession",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("game_session", "position_x", "position_y", "position_z")
                },
            },
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                ("move_id", models.AutoField(primary_key=True, serialize=False)),
                ("move_time", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("select", "Select Tile"),
                            ("match", "Match Tiles"),
                            ("reshuffle", "Reshuffle Board"),
                            ("withdraw", "Withdraw Selection"),
                            ("add_buffer", "Add Buffer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "game_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.gamesession",
                    ),
                ),
                (
                    "tile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.tile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gamesession",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.level"
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.player"
            ),
        ),
    ]
