# Generated by Django 4.2.7 on 2025-03-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="layer",
            field=models.IntegerField(default=0),
        ),
    ]
