# Generated by Django 4.2.7 on 2025-03-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_remove_gamesession_layer_tile_layer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="move",
            name="action",
            field=models.CharField(
                choices=[
                    ("select", "Select Tile"),
                    ("match", "Match Tiles"),
                    ("use_remove_tool", "Use Remove Tool"),
                    ("use_withdraw_tool", "Use Withdraw Tool"),
                    ("use_shuffle_tool", "Use Shuffle Tool"),
                ],
                max_length=20,
            ),
        ),
    ]
