# Generated by Django 4.2.7 on 2025-03-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_alter_move_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="buffer",
            field=models.JSONField(default=list),
        ),
    ]
