# Generated by Django 4.2.7 on 2025-03-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_gamesession_buffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="removed_tiles",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="move",
            name="action",
            field=models.CharField(
                choices=[
                    ("select", "Select Tile"),
                    ("match", "Match Tiles"),
                    ("use_remove_tool", "Use Remove Tool"),
                    ("use_withdraw_tool", "Use Withdraw Tool"),
                    ("use_shuffle_tool", "Use Shuffle Tool"),
                    ("return_removed_tile", "Return Removed Tile"),
                ],
                max_length=20,
            ),
        ),
    ]
